name: app-name

replicaCount: 1

deployment: {}

container:
  image:
    repository: repository_name/image
    tag: tag

global:
  imagePullPolicy: IfNotPresent

EnableMutilpleIngress: false
#EnableMutilpleIngress: true
#ingress:
#  internal-ingress:
#    annotations:
#      kubernetes.io/ingress.class: alb
#    rules:
#      - host:
#        http:
#          paths:
#          - backend:
#              serviceName: example
#              servicePort: 80
#            path: /health_check
#  external-ingress:
#    annotations:
#      kubernetes.io/ingress.class: alb
#    rules:
#      - host:
#        http:
#          paths:
#          - backend:
#              serviceName: example
#              servicePort: 80
#            path: /health_check


pdb:
  # If you just set "enable: true", default will set to "minAvailable: 50%" unless you have set other parameters.
  enable: false
  # Note: You can specify only one of maxUnavailable and minAvailable in a single PodDisruptionBudget, and if you setting both will only set maxUnavailable.
  # minAvailable: 50%
  # maxUnavailable: 50%