kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: role-{{ .Release.Name }}-po
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""] 
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""] 
    resources: ["pods/exec"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: role-binding-{{ .Release.Name }}-po
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: Group
    name: group-{{ .Release.Name }}-po
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-{{ .Release.Name }}-po
  apiGroup: rbac.authorization.k8s.io
