{{- if .Values.KEDA }}
  {{- if (and .Values.KEDA.ScaledObject (or .Values.hpa .Values.hpav2)) }}
    {{ fail "Don't create ScaledObject and HPA at same time." }}
  {{- end }}
  {{- if .Values.KEDA.ScaledObject }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec: {{ toYaml .Values.KEDA.ScaledObject.spec | nindent 2 }}
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ .Values.name }}
  {{- end }}
{{- end }}