{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key | quote }} : {{ $value | quote }}
  {{- end }}
{{- end}}