apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
  {{- if hasKey .Values.deployment "strategy" }}
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  {{- else}}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  {{- end}}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
{{- if hasKey .Values.deployment "containers" }}
  {{- range .Values.deployment.containers }}
      - {{ template "deployment.container" . }}
  {{- end}}
{{- else}}
      - {{ template "deployment.container_legacy" .Values }}
{{- end}}
      {{- if hasKey .Values.deployment  "volumes" }}
      volumes:
        {{- range $key, $vol := $.Values.deployment.volumes }}
        - name: {{ $vol.name }}
          configMap:
            name: {{ $vol.name }}
        {{- end }}
      {{- end }}
      restartPolicy: Always
