{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  {{- if hasKey .Values.service "type" }}
  type: {{ .Values.service.type }}
  {{- end }}
  selector:
    app: {{ .Values.name }}
{{- end }}